name: Update Crypto Charts

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:  # Allows manual runs

jobs:
  update-charts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run chart update scripts
        env:
          COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
        run: |
          python run_charts.py

      - name: Commit and push updated charts
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/charts/*.html
          git commit -m "Daily chart updates: $(date)" || echo "No changes to commit"
          git push
