name: Update Crypto Chart

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:  # Allows manual runs

jobs:
  update-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run chart update script
        env:
          COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
        run: python update_chart.py

      - name: Commit and push updated chart
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add crypto_performance.html historical_data.json
          git commit -m "Daily chart update: $(date)" || echo "No changes to commit"
          git push
